### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-doc#1]
I've been thinking for a while about the documentation and would like to submit a first draft.

As you'll see, nothing's very new here. I took some ideas from the F# foundation tutorials, ReasonML, Haxe, and many other sources and tried to come with something that could appeal to a newcomer like I was: foreign to .NET and clearly not a JS expert. So it could be anyone out there.

### Fable doc table of contents

- Introduction 
     - What is Fable?
     - Setup
     - Tools
     - Try Fable
- New to F#? 
     - Basic Types & Literals
     - Functions
     - Pipes
     - Pattern Matching
     - Collections
     - High order functions
     - Tuples
     - Records & anonymous records
     - Discriminated Unions
     - Union Types
     - Exceptions
     - Classes & Inheritance
     - Interfaces 
     - Active Patterns
- Fable for .NET users
     - babel
     - webpack
     - js imports
- Fable for JS users
     - syntax cheatsheet
     - converting from JS
     - solution files 
     - project files
     - paket
- Get started with...
     - Browser
     - Promises
     - Regexes (?)
     - Dates (?)
     - Json with Thoth.Json
     - Json with Fable.SimpleJson
     - Http requests with Fetch 
     - React
          - Charting with Recharts
          - Bulma Css with Fulma 
     - Elm architecture: Elmish
          - Hot Module Reload
          - Browser
          - Redux debugger
          - React
     - Node.js
- Interop with Javascript
     - Using external Javascript code
     - Using external libraries
     - Interop primer
          - Dynamic typing
          - Emit
          - Type-safe javascript functions
          - StringEnum
          - Create object literals
          - ts2fable
- Tutorials
     - Fable 101
          - My first Fable app
     - Fable Expert
          - Fable & Type Providers
               - Fable.JsonProvider
          - Fable Compiler for dummies
               - ?
          - Full stack on .NET with the SAFE stack
          - Fable on Node.js
          - Fable with Express
     - Fable Next
          - Fable on IBM Functions

- Extra 
     - FAQ
     - Awesome resources

### Disclaimer
Since we are located at the crossroad of JS and .NET users, I'd like to address both. Why would I propose that? Simply because I'm not a .NET user. I went directly to fsharp straight from Fable. Then I learnt a thing or two about .NET but still I do not consider myself a .NET user. :wink 

I think that things may be missing or may not be necessary here. So please tell me what you think. Thanks!

@alfonsogarciacaro @MangelMaxime @selketjah @Zaid-Ajaj @forki @Krzysztof-Cieslak 

[EDIT]: [toc draft file](https://github.com/fable-compiler/fable-doc/blob/master/wip/toc.md)

**Comment by MangelMaxime** [comment]
Great work @whitetigle 

I like that the Fable docs can become something self-sufficient. This will need a lot of work to kick off but then it can be something really powerful 😍

**Comment by MangelMaxime** [comment]
I would encourage us to have a menu displayed on the website of 2-3 levels max.

Demo:

**Section**
- Item1
     - Item1.1
     - Item1.2
- Item2
     - Item2.1
     - Item22

**Section**
- Item1
- Item2

With more level the menu will be to big or be to specific. 

I know that you say TOC and not menu but after working a tool to generate docs site for a while now I think this is something really important to note :)

**Comment by selketjah** [comment]
Great start! I think 8 top levels is too much, but how much is good is also a bit of a mystery to me. My instinct says 3 or 4 is what we should aim for...

Having a couple of scenario's with users could be helpful here:

1. I am a developer in .NET and my colleague told me to check out something called Fable.
2. I am a front end dev with no .NET experience and I want to check out Fable
3. I know Fable and I have a very specific question I want to see answered.
4. I know what Fable is, but I have all these options available, and I want to know if my project would benefit from using Fable.

From possible scenario's we can start making decisions for the top level:
I would not have something called "New to F#" as a first level considering these scenario's.
But if the user has no .NET experience, we could offer possible resource. We don't want to provide them ourselves, that would take time and effort and we want to focus on Fable. _fsharpforfunandprofit_ is a wonderful example of good documentation we could link to. MSDN is also one.

Will think about it a bit more and come up with some better scenario's most are too vague, this is just a bit of a mind dump for now ;-)

**Comment by MangelMaxime** [comment]
>  fsharpforfunandprofit is a wonderful example of good documentation we could link to. MSDN is also one.

Personally, I use the MSDN documentation only if I know what I am looking for because I find it really hard to navigate in.

About fsharpforfunandprofit the content is really great indeed. But compared to "recent documentation" finding something in it is hard too. 
For comparaison:
- [Reason main docs page](https://reasonml.github.io/docs/en/what-and-why)
- [fsharpforfunandprofit - root](https://fsharpforfunandprofit.com/)
- [fsharpforfunandprofit - Learning Fsharp](https://fsharpforfunandprofit.com/learning-fsharp/)

If you are a new user, fsharpforfunandprofit looks a lot like a single/compact block of text. I don't know if Scott is willing to update fsharpforfunandprofit or no. But if no, I would rather have us host the minimal documentation required to understand F# and link to page to fsharpforfunandprofit and MSDN in a `Advance documentation` or `To go further` section at the bottom of the sections.

Also, hosting the documentation about variables / record allows us to mention Fable specificities if needed. And allow us to say here is what your F# code is and the JavaScript is this one.

**Comment by whitetigle** [comment]
Hi thank you very much for your helpful comments! 

Like @MangelMaxime  wrote, regarding ""New To F#" the main goal in my mind is to give contextual samples using Fable ; something related to the javascript/Fable context. For instance Pattern matching to handle canvas drawing operations, Collections to filter html elements and so on. And maybe more things related to Fable libraries like Elmish, React, Fulma, JSON, etc... And then, as you said, we could add to this links to fsharpforfunandprofit, microsoft help and MSDN to allow the user to find further generic information.

> From possible scenario's we can start making decisions for the top level:

Excellent idea. I'll think about it a little bit and see what I can come with. I also agree that 3 or 4 top levels should suffice. 

Thanks again for taking time to share your thoughts ! ❤️

**Comment by nojaf** [comment]
Maybe also consider a small section of `coming from TypeScript`.
There I would explain how you can use ts2fable where you would you `@types` instead.
And mention that sometimes it is sometimes easier to create you own little wrapper over a JS library than reconstructing all the correct types from a d.ts file.

I had this experience trying to use express and mysql past weekend. Tried to convert TypeScript typings but that was composed out of multiple files, which is not supported.
For example:
```ts
import "fooModule" from "./foo.d.ts"
```
Ending up creating a little wrapper in js and imported that function in Fable. Quick and easier than trying to reconstruct all the types.

**Comment by MangelMaxime** [comment]
> Tried to convert TypeScript typings but that was composed out of multiple files, which is not supported.

This is supported by ts2fable. Passing the `-e` entry or something like that.

**Comment by whitetigle** [comment]
TOC TAKE 2 😃 

> 1 - I am a developer in .NET and my colleague told me to check out something called Fable.
2 - I am a front end dev with no .NET experience and I want to check out Fable
3 - I know Fable and I have a very specific question I want to see answered.
4 - I know what Fable is, but I have all these options available, and I want to know if my project would benefit from using Fable.



### Fable doc table of contents

- Discover Fable 
  - What is Fable?
  - Setup
  - Tools
  - Try Fable
  - FAQ
  - Awesome resources    
- Use Fable
  - Use F#
    - Introduction
    - Basic Types & Literals
    - Functions
    - Pipes
    - Pattern Matching
    - Collections
    - Units of measure
    - High order functions
    - Tuples
    - Records & anonymous records
    - Discriminated Unions
    - Union Types
    - Exceptions
    - Classes & Inheritance
    - Interfaces 
    - Active Patterns
    - Converting from JS (syntax cheatsheet)
  - Anatomy of a Fable project
    - introduction 
    - babel
    - webpack
    - solution files 
    - project files
    - paket
    - fake
    - js imports
  - Fable for frontend
    - Browser
    - Promises
    - Regexes 
    - Dates 
    - Json with Thoth.Json
    - Json with Fable.SimpleJson
    - Json with Fable.JsonProvider
    - Http requests with Fetch 
    - React
    - Charting with Recharts
    - Styling with Fulma
    - Elm architecture with Elmish
    - My first complete Fable app
  - Fable for scripting
      - Fable on Node.js    
  - Fable for backend
    - Full stack on .NET with the SAFE stack
    - Fable with Express
    - Fable on Node.js    
  - Fable for gaming
  - Fable on Faas cloud
    - IBM
    - Azure 
    - Google 
    - AWS
- Interoperability 
  - Use external Javascript code
  - Use external libraries
  - Interop 101
    - Discover Dynamic typing
    - Emit
    - Type-safe javascript functions
    - StringEnum
    - Create object literals
  - From Typescript
    - ts2fable

**Comment by MangelMaxime** [comment]
I think we could name the section "Anatomy of a Fable project > Fake" into something like "Anatomy of a Fable project > Build system"?

My motivation being this proposition is that nothing force the user to use FAKE, he can use "npm scripts" or FAKE or "Fable scripts"

**Comment by MangelMaxime** [comment]
What's the difference between "Fable for scripting > Fable on Node.js" or "Fable for backend > Fable on Node.js"?

I think using:

* Fable for scripting  
    * Fable on Node.js

* Fable for backend
  * Full stack on .NET with the SAFE stack
  * Fable with Express

Is good enough no?

**Comment by MangelMaxime** [comment]
What's the difference between "Use external Javascript code" and "Use external libraries" ?

**Comment by whitetigle** [comment]
> What's the difference between "Use external Javascript code" and "Use external libraries" ?
You're right, no need to make a difference. We can simplify.

Thanks @MangelMaxime!

**Comment by whitetigle** [comment]
TOC TAKE 3 😃 

> 1 - I am a developer in .NET and my colleague told me to check out something called Fable.
2 - I am a front end dev with no .NET experience and I want to check out Fable
3 - I know Fable and I have a very specific question I want to see answered.
4 - I know what Fable is, but I have all these options available, and I want to know if my project would benefit from using Fable.



### Fable doc table of contents

- Discover Fable 
  - What is Fable?
  - Setup
  - Tools
  - Try Fable
  - FAQ
  - Awesome resources    
- Use Fable
  - Use F#
    - Introduction
    - Basic Types & Literals
    - Functions
    - Pipes
    - Pattern Matching
    - Collections
    - Units of measure
    - High order functions
    - Tuples
    - Records & anonymous records
    - Discriminated Unions
    - Union Types
    - Exceptions
    - Classes & Inheritance
    - Interfaces 
    - Active Patterns
    - Converting from JS (syntax cheatsheet)
  - Anatomy of a Fable project
    - introduction 
    - babel
    - webpack
    - solution files 
    - project files
    - paket
    - **Build System**
  - Fable for frontend
    - Browser
    - Promises
    - Regexes 
    - Dates 
    - Json with Thoth.Json
    - Json with Fable.SimpleJson
    - Json with Fable.JsonProvider
    - Http requests with Fetch 
    - React
    - Charting with Recharts
    - Styling with Fulma
    - Elm architecture with Elmish
    - My first complete Fable app
  - Fable for scripting
      - Fable on Node.js    
  - Fable for backend
    - Full stack on .NET with the SAFE stack
    - Fable with Express
  - Fable for gaming
  - Fable on Faas cloud
    - IBM
    - Azure 
    - Google 
    - AWS
- Interoperability 
  - Use external Javascript code
  - Interop 101
    - Discover Dynamic typing
    - Emit
    - Type-safe javascript functions
    - StringEnum
    - Create object literals
  - From Typescript
    - ts2fable

**Comment by whitetigle** [comment]
ok if everybody is ok, I'll start with this.

**Comment by MangelMaxime** [comment]
For me it's all good and even if we move a bit the categories, 90% of the content will be the same as we know it will have to be included one way or another :)

**Comment by whitetigle** [comment]
ok. Thanks @MangelMaxime

**Comment by MangelMaxime** [comment]
@whitetigle Finally, Nacara will support "3 levels" menu. Like it's done for [Fulma](https://fulma.github.io/Fulma/#home).

**Comment by whitetigle** [comment]
perfect! 👍

**Comment by francisl** [comment]
Hey, 

I'm a bit late to the conversation, but if it can help, here is my 2 cents. 

For little background, I'm mostly a JS developer with a background with exclusively dynamic language with some exceptions in hobby project. I have a strong interest to learn a ml language and I first begin with ocaml/reasonml. But I decided to go with fable, because of the potential of using F# in different scenario. 

That said, I would like to add that the current structure looks great. But here is some trouble I had getting started with reason and fable. I hope it can help guiding the doc and helping new comers.   

- JavaScript object vs ml one. In JS we use object for everything, struct, record, object. The mapping to reason was not obvious at first
- How to migrate gradually an existing project
   e.g. creating a react-component than load in an already existing js app 
- How to re-use types definition 
- Async/Await | promise 
- How to import other files 
- In fable I couldn't find information on what are the .net project file and I had to copy paste from some github project in hope to get it working.

One improvement I'd like to suggest, is to remove the TS section and have a section about working with types. 
e.g. 

**Types** 
- Use JS without type safety (if possible) 
- Create your own type binding 
- Reuse type from TypeScript 

Maybe this is what `interop 101` is, but with a JS background, this section wording is fuzzy

**Comment by whitetigle** [comment]
Thanks for the feedback @francisl! 

> I hope it can help guiding the doc and helping new comers.
Definitely!

> One improvement I'd like to suggest, is to remove the TS section and have a section about working with types.
That was indeed the purpose of `interop101` but if the name's not good enough we can change that to something better. Same things regarding the topics. For instance, **Dynamic typings** could be renamed to **JS without type safety**.

I think it's really important to get a real good TOC and proper section names and I'm happy your experience as a JS dev learning F# can help us to make that much better. 

So if you had to refine the TOC, what would you add/remove/change so that it gets clearer?

**Comment by whitetigle** [comment]
[For info WIP here](https://github.com/fable-compiler/fable-doc/wiki/Fable-Documentation)

**Comment by whitetigle** [comment]
Hi so far I've made a tour of a common Fable project adressing both .NET & javascript users. I've also changed the Table of Contents a little bit to make the reading process more logical as a first time user.

You can see the current state of the doc [here](https://github.com/fable-compiler/fable-doc/wiki/Fable-documentation.). Please feel free to comment, modifiy, correct, etc... Thanks!

On a side note, I'm not fond of the current state of the Build & Run article which appears to me as too vague. If you have ideas I'm ready to hear them.

I think the next priority will be interop so that we we'll be able to create a first full working version of the doc with current Fable.Core allowing us to replace the current docs & FAQ links with a link to this repo as there are many information which unfortunately are out of date. Nothing illogical here since the project is evolving very fast.

Have a nice day!

**Comment by whitetigle** [comment]
I've just updated the doc with a full interop round both from JS>Fable and Fable>js.

**Comment by whitetigle** [comment]
Ok I'll close this topic. If anybody wants to add some new articles to the current TOC, please open an issue or send your PR. Thanks for your help! 😃 👍
