### ISSUE TITLE
Nacara custom features

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-doc#12]
@MangelMaxime, I was reading doc about Next.js and I like their [very easy to use yet not very original FAQ](https://nextjs.org/docs#faq=)
How easy is it to add custom features so that we can create components out of markdown files just like the `[[toc]]` keyword in Nacara ?

**Comment by MangelMaxime** [comment]
Well `[[toc]]` is more or less already doing the same. You just have the menu on the right instead no? :)

You can't add custom feature yet. You need to wait until the plugin system is in place in order to do that.

**Comment by whitetigle** [comment]
> Well [[toc]] is more or less already doing the same. You just have the menu on the right instead no? :)

Well, in terms of UX it's very different :). 

> You can't add custom feature yet. You need to wait until the plugin system is in place in order to do that.

Great! Can't wait to add some webasssembly based 3D rotating Fable logo when I add the `[[fable]]` marker! 😝

**Comment by MangelMaxime** [comment]
@whitetigle Ah but I didn't see the FAQ because your URL is invalid :p (You have a trailing `=`)

If you open an issue on Nacara, to track it, it could be nice :) So I remember to add/test it.

> > You can't add custom feature yet. You need to wait until the plugin system is in place in order to do that.
> 
> Great! Can't wait to add some webasssembly based 3D rotating Fable logo when I add the `[[fable]]` marker! 😝

Perhaps, I should forbid you to create plugins :p

**Comment by whitetigle** [comment]
> Perhaps, I should forbid you to create plugins :p

😭 😭 😭 

> If you open an issue on Nacara, to track it, it could be nice :) So I remember to add/test it.

[Done](https://github.com/MangelMaxime/Nacara/issues/9) 😄
