### ISSUE TITLE
Want to help with the doc? Read this!

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-doc#2]
Hi there!
As part of the writing process we'd like to gather feedback from you as a .NET developer or JS developer or in any case as an awesome developer, because that's what you are! So in other words, we need your help! 😉 

Please take time to read the current documentation and raise an issue whenever you feel the need to comment on an article.

The current documentation is written as part of the github hosted wiki so that it should be easy to read it and review it.

Once everybody's happy with the changes, we'll publish as a full doc site using @MangelMaxime great doc system.

Interested? [here's the link to the wiki](https://github.com/fable-compiler/fable-doc/wiki/Fable-documentation.)!

Thank you! We're waiting for your feedback! 🌞

**Comment by MangelMaxime** [comment]
We can stop using the Wiki :)

If you want to contribute please edit the files in `docsrc` folder :).
Also, it's possible to have a preview of the documentation [here](http://fable.io/fable-doc/). Please note, that improvements are planned in Nacara and in the style used by the website. So the look  isn't polish yet but it can give a good idea of what is to come :)
