### ISSUE TITLE
Ignore lockfile?

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable-doc#5]
Hi @whitetigle , I've read https://github.com/fable-compiler/fable-doc/wiki/Start-a-new-project-using-templates#step-2-install-js-dependencies and you mentioned that the `package-lock.json` can be added to the `.gitignore` file.

Are you sure about that? If I recall we like lock files, f.ex in [Fable repo](https://github.com/fable-compiler/Fable/blob/master/package-lock.json).

**Comment by alfonsogarciacaro** [comment]
@nojaf is right, the lock file should be committed to ensure reproducible builds whenever anybody clones the repo

**Comment by whitetigle** [comment]
Indeed you're absolutely right. I'll change this! Thanks guys!

**Comment by whitetigle** [comment]
[Done](https://github.com/fable-compiler/fable-doc/pull/8)
